In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Example job description and candidate's resume
job_description = "Looking for a software engineer proficient in Python and machine learning"
resume = "Experienced software engineer with expertise in Python programming and machine learning algorithms"

# Convert job description and resume into a list
documents = [job_description, resume]

# Initialize CountVectorizer to convert text into a bag of words
vectorizer = CountVectorizer()

# Fit and transform the documents into a matrix of token counts
matrix = vectorizer.fit_transform(documents)

# Compute cosine similarity between job description and resume
cos_sim = cosine_similarity(matrix)

# The cosine similarity matrix
print("Cosine Similarity Matrix:")
print(cos_sim)

# Extract cosine similarity value for job description and resume
job_resume_similarity = cos_sim[0, 1]
print(f"\nCosine Similarity between Job Description and Resume: {job_resume_similarity}")


Cosine Similarity Matrix:
[[1.         0.63900965]
 [0.63900965 1.        ]]

Cosine Similarity between Job Description and Resume: 0.6390096504226939


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Example job description and candidate's resume
job_description = "Looking for a software engineer proficient in Python and machine learning"
resume = "Experienced software engineer with expertise in Python programming and machine learning algorithms"

# Convert job description and resume into a list
documents = [job_description, resume]

# Initialize TfidfVectorizer to convert text into TF-IDF features
vectorizer = TfidfVectorizer()

# Fit and transform the documents into a TF-IDF matrix
tfidf_matrix = vectorizer.fit_transform(documents)

# Compute cosine similarity between job description and resume using TF-IDF
cos_sim_tfidf = cosine_similarity(tfidf_matrix)

# The cosine similarity matrix using TF-IDF
print("Cosine Similarity Matrix (TF-IDF):")
print(cos_sim_tfidf)

# Extract cosine similarity value for job description and resume
job_resume_similarity_tfidf = cos_sim_tfidf[0, 1]
print(f"\nCosine Similarity between Job Description and Resume (TF-IDF): {job_resume_similarity_tfidf}")


Cosine Similarity Matrix (TF-IDF):
[[1.         0.47393934]
 [0.47393934 1.        ]]

Cosine Similarity between Job Description and Resume (TF-IDF): 0.4739393421029532


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import re

# Example job description and candidate's resume
job_description = "Looking for a software engineer proficient in Python and machine learning"
resume = "Experienced software engineer with expertise in Python programming and machine learning algorithms"

# Preprocessing function to clean text
def preprocess_text(text):
    # Convert text to lowercase
    text = text.lower()
    # Remove non-alphanumeric characters and extra whitespaces
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    return text

# Preprocess job description and resume
clean_job_description = preprocess_text(job_description)
clean_resume = preprocess_text(resume)

# Convert job description and resume into a list
documents = [clean_job_description, clean_resume]

# Initialize TfidfVectorizer to convert text into TF-IDF features
vectorizer = TfidfVectorizer()

# Fit and transform the documents into a TF-IDF matrix
tfidf_matrix = vectorizer.fit_transform(documents)

# Compute cosine similarity between job description and resume using TF-IDF
cos_sim_tfidf = cosine_similarity(tfidf_matrix)

# The cosine similarity matrix using TF-IDF
print("Cosine Similarity Matrix (TF-IDF):")
print(cos_sim_tfidf)

# Extract cosine similarity value for job description and resume
job_resume_similarity_tfidf = cos_sim_tfidf[0, 1]
print(f"\nCosine Similarity between Job Description and Resume (TF-IDF): {job_resume_similarity_tfidf}")


Cosine Similarity Matrix (TF-IDF):
[[1.         0.47393934]
 [0.47393934 1.        ]]

Cosine Similarity between Job Description and Resume (TF-IDF): 0.4739393421029532


Cosine simalirity

In [ ]:
import numpy as np
from numpy.linalg import norm

# Two example vectors representing documents
vector_a = np.array([2, 1, 0, 2, 2])  # Vector representation of document A
vector_b = np.array([3, 1, 1, 0, 2])  # Vector representation of document B

# Calculate dot product of the two vectors
dot_product = np.dot(vector_a, vector_b)

# Calculate the magnitudes of the vectors
magnitude_a = norm(vector_a)
magnitude_b = norm(vector_b)

# Calculate cosine similarity
cosine_similarity = dot_product / (magnitude_a * magnitude_b)

print(f"Cosine Similarity between the two vectors: {cosine_similarity}")


Cosine Similarity between the two vectors: 0.7877263614433762


#Cosine Simalrity

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Example job description and candidate's resume
job_description = "Looking for a software engineer proficient in Python and machine learning"
resume = "Experienced software engineer with expertise in Python programming and machine learning algorithms"

# Convert job description and resume into a list
documents = [job_description, resume]

# Initialize CountVectorizer to convert text into a bag of words (word frequencies)
vectorizer = CountVectorizer()

# Fit and transform the documents into a matrix of word frequencies
matrix = vectorizer.fit_transform(documents)

# Get the word frequency vectors for the job description and resume
job_vector = matrix[0].toarray().flatten()  # Vector representation of job description
resume_vector = matrix[1].toarray().flatten()  # Vector representation of resume

# Calculate cosine similarity between job description and resume
cos_sim = cosine_similarity([job_vector], [resume_vector])

print(f"Cosine Similarity between Job Description and Resume: {cos_sim[0][0]}")


Cosine Similarity between Job Description and Resume: 0.6390096504226939


In [ ]:
job_vector

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0])

In [ ]:
resume_vector

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1])

# Jaccard Similarity

In [ ]:
# Example sets representing words in two documents
doc_a = set(['apple', 'banana', 'orange', 'pear'])
doc_b = set(['banana', 'orange', 'grape', 'watermelon'])

# Calculate Jaccard Similarity
intersection = len(doc_a.intersection(doc_b))  # Number of common elements
union = len(doc_a.union(doc_b))  # Total unique elements

jaccard_similarity = intersection / union
print(f"Jaccard Similarity between the two sets: {jaccard_similarity}")


Jaccard Similarity between the two sets: 0.3333333333333333


# Euclidean Distance

In [ ]:
import numpy as np

# Coordinates of two points in a 2D space
point_a = np.array([1, 2])
point_b = np.array([4, 6])

# Calculate Euclidean Distance
euclidean_distance = np.linalg.norm(point_a - point_b)
print(f"Euclidean Distance between the two points: {euclidean_distance}")


Euclidean Distance between the two points: 5.0


# TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Example documents
documents = [
    "This is the first document.",
    "This document is the second document.",
    "And this is the third one.",
    "Is this the first document?",
]

# Initialize TfidfVectorizer to convert text into TF-IDF features
vectorizer = TfidfVectorizer()

# Fit and transform the documents into TF-IDF matrices
tfidf_matrix = vectorizer.fit_transform(documents)

# Print the TF-IDF matrix
print("TF-IDF Matrix:")
print(tfidf_matrix.toarray())

# Get feature names (words)
feature_names = vectorizer.get_feature_names_out()
print("\nFeature Names:")
print(feature_names)


TF-IDF Matrix:
[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]

Feature Names:
['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


#Practice

In [ ]:
!pip install PyPDF2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 3.7 MB/s eta 0:00:00


In [ ]:
import PyPDF2
import re
import nltk
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('stopwords')

# Function to extract text from a PDF file
def extract_text_from_pdf(file_path):
    with open(file_path, 'rb') as file:
        reader = PyPDF2.PdfReader(file)
        num_pages = len(reader.pages)
        text = ''
        for page_num in range(num_pages):
            page = reader.pages[page_num]
            text += page.extract_text()
    return text

# Function to preprocess text
def preprocess_text(text):
    # Convert text to lowercase
    text = text.lower()
    # Remove non-alphanumeric characters and extra whitespaces
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    return text

# Function to calculate Jaccard Similarity
def jaccard_similarity(set_a, set_b):
    intersection = len(set_a.intersection(set_b))
    union = len(set_a.union(set_b))
    return intersection / union if union != 0 else 0

# Input file paths for resume PDF and job description text
resume_file_path = '/content/SIddhesh Mhatre.pdf'  # Replace with the path to your resume PDF
job_description = '''Design, develop, and implement high-quality software solutions using Python, Java, React, GraphQL, and other cutting-edge technologies.
Collaborate with cross-functional teams to understand requirements and deliver exceptional products.
Write clean, maintainable, and well-documented code.
Test and debug software to ensure functionality and performance.
Stay up-to-date with the latest technologies and best practices.
Here's what you'll bring: Bachelor's degree in Information Technology or a related field (Master's degree preferred).
Proven experience in software development, with a strong portfolio of projects.
Proficiency in Python, Java, React, GraphQL, and MySQL.
Experience with machine learning and natural language processing is a plus.
Excellent problem-solving, analytical, and communication skills.
Ability to work independently and as part of a team.
Adaptability to changing requirements and deadlines.''' # Replace with your job description

# Extract text from resume PDF
resume_text = extract_text_from_pdf(resume_file_path)

# Preprocess resume and job description text
cleaned_resume = preprocess_text(resume_text)
cleaned_job_description = preprocess_text(job_description)

# Tokenize cleaned text
tokenized_resume = word_tokenize(cleaned_resume)
tokenized_job_description = word_tokenize(cleaned_job_description)

# Create sets of tokens for Jaccard Similarity
set_resume = set(tokenized_resume)
set_job_description = set(tokenized_job_description)

# Calculate cosine similarity using TF-IDF
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform([cleaned_resume, cleaned_job_description])
cosine_sim_tfidf = cosine_similarity(tfidf_matrix)[0, 1]

# Calculate Jaccard Similarity
jaccard_sim = jaccard_similarity(set_resume, set_job_description)

# Calculate Euclidean Distance
vectorizer = CountVectorizer()
count_matrix = vectorizer.fit_transform([cleaned_resume, cleaned_job_description]).toarray()
euclidean_distance = np.linalg.norm(count_matrix[0] - count_matrix[1])

# Display similarity scores
print(f"Cosine Similarity (TF-IDF): {cosine_sim_tfidf}")
print(f"Jaccard Similarity: {jaccard_sim}")
print(f"Euclidean Distance: {euclidean_distance}")


Cosine Similarity (TF-IDF): 0.09245749254649388
Jaccard Similarity: 0.05128205128205128
Euclidean Distance: 18.681541692269406


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Cosine Similarity (TF-IDF) indicates relatively low similarity between the resume and job description in the context of word importance.
Jaccard Similarity shows a low overlap of unique words between the two texts.
Euclidean Distance suggests significant dissimilarity between the word frequency vectors of the resume and job description.

Practice

In [ ]:
# Job description and resume text
job_description = """
We are seeking a skilled Python Developer to join our dynamic team. As a Python Developer, you will be responsible for developing and maintaining high-quality software applications, utilizing your expertise in Python programming. The ideal candidate should have a strong foundation in Python, excellent problem-solving abilities, and a passion for creating efficient and scalable solutions.
"""

resume_text = """
SIDDHESH MHATRE
SOFTWARE DEVELOPER
...
Skills
Languages Python , java, pandas ,HTML/CSS, MySQL
...
Experience
Infogen Labs Inc remote
MACHINE LEARNING INTERNSHIP Dec 2023 - Present
• Engaged in developing and implementing machine learning models for data analysis tasks.
• Completed self-paced projects in Python focusing on data prepossessing and basic machine learning models (e.g., regression, classification.
...
Projects
Dog Skin Diseases Detection and Identification using CNN
...
ResuMatch - AI-Powered Resume Selection
...
Achievements
Publication: Springer Scopus (ICACI-2022)
...
Certifications
• GraphQL with React and Node js - View
...
"""

# Define key skills and qualifications from the job description
key_skills = ['Python', 'problem-solving', 'software development', 'front-end technologies', 'Bachelor', 'communication', 'teamwork']

# Extracting relevant sections from the resume
skills_section_start = resume_text.find('Skills')
experience_section_start = resume_text.find('Experience')
certifications_section_start = resume_text.find('Certifications')

skills_section = resume_text[skills_section_start:experience_section_start]
experience_section = resume_text[experience_section_start:certifications_section_start]
# Extracting skills from the skills section
extracted_skills = [skill.strip() for skill in skills_section.split('\n') if any(keyword.lower() in skill.lower() for keyword in key_skills)]

# Matching qualifications and skills with the job description
matched_qualifications = [qualification for qualification in key_skills if any(qualification.lower() in resume_text.lower() for qualification in key_skills)]

# Check if all key skills are found in the resume
all_skills_matched = all(skill.lower() in resume_text.lower() for skill in key_skills)

# Check eligibility based on matching qualifications
if len(matched_qualifications) >= len(key_skills) * 0.7:
    eligibility_status = "Eligible"
else:
    eligibility_status = "Not Eligible"

# Print extracted skills, matched qualifications, and eligibility status
print("Extracted Skills from Resume:", extracted_skills)
print("Matched Qualifications:", matched_qualifications)
print("Eligibility Status:", eligibility_status)


Extracted Skills from Resume: ['Languages Python , java, pandas ,HTML/CSS, MySQL']
Matched Qualifications: ['Python', 'problem-solving', 'software development', 'front-end technologies', 'Bachelor', 'communication', 'teamwork']
Eligibility Status: Eligible


In [ ]:
matched_qualifications

['Python',
 'problem-solving',
 'software development',
 'front-end technologies',
 'Bachelor',
 'communication',
 'teamwork']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import re

# Job description and resume text
job_description = """
Job Title: Python Developer

Job Description:

We are seeking a skilled Python Developer to join our dynamic team. As a Python Developer, you will be responsible for developing and maintaining high-quality software applications, utilizing your expertise in Python programming. The ideal candidate should have a strong foundation in Python, excellent problem-solving abilities, and a passion for creating efficient and scalable solutions.

Responsibilities:

Design, develop, and implement software solutions using Python programming language.
Collaborate with cross-functional teams to define, design, and ship new features.
Troubleshoot, debug, and enhance existing software applications.
Write clean, maintainable, and efficient code.
Participate in code reviews and provide constructive feedback.
Requirements:

Bachelor's degree in Computer Science, Engineering, or related field.
Proven experience as a Python Developer or similar role.
Proficient in Python programming with a deep understanding of Python libraries and frameworks.
Familiarity with front-end technologies (such as JavaScript, HTML, CSS) is a plus.
Strong problem-solving skills and attention to detail.
Excellent communication and teamwork abilities.
Benefits:

Competitive salary package.
Opportunity to work on cutting-edge projects.
Career growth and development opportunities.
Health insurance and other benefits.

"""

resume_text = """
SIDDHESH MHATRE
SOFTWARE DEVELOPER
...
Skills
Languages Python , java, pandas ,HTML/CSS, MySQL
...
Experience
Infogen Labs Inc remote
MACHINE LEARNING INTERNSHIP Dec 2023 - Present
• Engaged in developing and implementing machine learning models for data analysis tasks.
• Completed self-paced projects in Python focusing on data prepossessing and basic machine learning models (e.g., regression, classification.
...
Projects
Dog Skin Diseases Detection and Identification using CNN
...
ResuMatch - AI-Powered Resume Selection
...
Achievements
Publication: Springer Scopus (ICACI-2022)
...
Certifications
• GraphQL with React and Node js - View
...
"""

# Preprocess text (remove non-alphanumeric characters and convert to lowercase)
def preprocess_text(text):
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    return text.lower()

# Preprocess job description and resume text
cleaned_job_description = preprocess_text(job_description)
cleaned_resume_text = preprocess_text(resume_text)

# Create TF-IDF vectors for job description and resume
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform([cleaned_job_description, cleaned_resume_text])

# Calculate cosine similarity between job description and resume
cosine_sim = cosine_similarity(tfidf_matrix)[0, 1]

# Set a threshold for similarity score to determine eligibility
similarity_threshold = 0.5  # Adjust as needed

# Assess eligibility based on cosine similarity
if cosine_sim >= similarity_threshold:
    eligibility_status = "Eligible"
else:
    eligibility_status = "Not Eligible"

# Print cosine similarity and eligibility status
print(f"Cosine Similarity: {cosine_sim}")
print("Eligibility Status:", eligibility_status)


Cosine Similarity: 0.28330281750173014
Eligibility Status: Not Eligible


In [ ]:
cleaned_job_description

'\nwe want skill python devloper  as well know java  and data bases mysql  or must me experinced in machine learing\n'

In [ ]:
cleaned_resume_text

'\nsiddhesh mhatre\nsoftware developer\n\nskills\nlanguages python  java pandas htmlcss mysql\n\nexperience\ninfogen labs inc remote\nmachine learning internship dec 2023  present\n engaged in developing and implementing machine learning models for data analysis tasks\n completed selfpaced projects in python focusing on data prepossessing and basic machine learning models eg regression classification\n\nprojects\ndog skin diseases detection and identification using cnn\n\nresumatch  aipowered resume selection\n\nachievements\npublication springer scopus icaci2022\n\ncertifications\n graphql with react and node js  view\n\n'

Find similer word

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import re
import nltk
nltk.download('stopwords')

# Job description and resume text (same as before)
job_description = """
Python , java, pandas ,HTML/CSS, MySQL
"""

resume_text = """
SIDDHESH MHATRE
SOFTWARE DEVELOPER
...
Skills
Languages Python , java, pandas ,HTML/CSS, MySQL
...
Experience
Infogen Labs Inc remote
MACHINE LEARNING INTERNSHIP Dec 2023 - Present
• Engaged in developing and implementing machine learning models for data analysis tasks.
• Completed self-paced projects in Python focusing on data prepossessing and basic machine learning models (e.g., regression, classification.
...
Projects
Dog Skin Diseases Detection and Identification using CNN
...
ResuMatch - AI-Powered Resume Selection
...
Achievements
Publication: Springer Scopus (ICACI-2022)
...
Certifications
• GraphQL with React and Node js - View
...
"""

# Preprocess text (remove non-alphanumeric characters and convert to lowercase)
def preprocess_text(text):
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    return text.lower()

# Preprocess job description and resume text
cleaned_job_description = preprocess_text(job_description)
cleaned_resume_text = preprocess_text(resume_text)

# Create TF-IDF vectors for job description and resume
vectorizer = TfidfVectorizer(stop_words='english')  # Specify stopwords
tfidf_matrix = vectorizer.fit_transform([cleaned_job_description, cleaned_resume_text])

# Calculate cosine similarity between job description and resume
cosine_sim = cosine_similarity(tfidf_matrix)[0, 1]

# Get feature names (words) from TF-IDF vectorizer
feature_names = vectorizer.get_feature_names_out()

# Extract words contributing to similarity
similar_words_indices = tfidf_matrix[0].toarray().argsort(axis=1)[:, ::-1][:, :10]  # Adjust number of words displayed here
similar_words = [feature_names[idx] for idx in similar_words_indices.flatten()]

# Print cosine similarity, top similar words, and eligibility status
print(f"Cosine Similarity: {cosine_sim}")
print("Top Similar Words:", similar_words)


Cosine Similarity: 0.21076913581016138
Top Similar Words: ['java', 'htmlcss', 'mysql', 'pandas', 'python', 'view', 'infogen', 'implementing', 'identification', 'icaci2022']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


## Gove2

In [ ]:
import numpy as np
import re

# Load GloVe word vectors into a dictionary
glove_file_path = '/content/drive/MyDrive/GloveText/glove.txt'  # Replace with your GloVe file path
word_vectors = {}
with open(glove_file_path, 'r', encoding='utf-8') as f:
    for line in f:
        values = line.split()
        word = values[0]
        vector = np.asarray(values[1:], dtype='float32')
        word_vectors[word] = vector

# Job description and resume text (same as before)
job_description = """
We are seeking a skilled Python Developer to join our dynamic team. As a Python Developer, you will be responsible for developing and maintaining high-quality software applications, utilizing your expertise in Python programming. The ideal candidate should have a strong foundation in Python, excellent problem-solving abilities, and a passion for creating efficient and scalable solutions.

"""

resume_text = """
SIDDHESH MHATRE
SOFTWARE DEVELOPER
...
Skills
Languages Python , java, pandas ,HTML/CSS, MySQL
...
Experience
Infogen Labs Inc remote
MACHINE LEARNING INTERNSHIP Dec 2023 - Present
• Engaged in developing and implementing machine learning models for data analysis tasks.
• Completed self-paced projects in Python focusing on data prepossessing and basic machine learning models (e.g., regression, classification.
...
Projects
Dog Skin Diseases Detection and Identification using CNN
...
ResuMatch - AI-Powered Resume Selection
...
Achievements
Publication: Springer Scopus (ICACI-2022)
...
Certifications
• GraphQL with React and Node js - View
...
"""

# Preprocess text (remove non-alphanumeric characters and convert to lowercase)
def preprocess_text(text):
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    return text.lower()

# Preprocess job description and resume text
cleaned_job_description = preprocess_text(job_description)
cleaned_resume_text = preprocess_text(resume_text)

# Tokenize the cleaned text
tokenized_job_description = cleaned_job_description.split()
tokenized_resume_text = cleaned_resume_text.split()

# Calculate average word vectors for job description and resume
job_desc_vectors = [word_vectors[word] for word in tokenized_job_description if word in word_vectors]
resume_vectors = [word_vectors[word] for word in tokenized_resume_text if word in word_vectors]

if job_desc_vectors and resume_vectors:
    job_desc_avg_vector = sum(job_desc_vectors) / len(job_desc_vectors)
    resume_avg_vector = sum(resume_vectors) / len(resume_vectors)

    # Calculate cosine similarity between job description and resume
    cosine_sim = np.dot(job_desc_avg_vector, resume_avg_vector) / (np.linalg.norm(job_desc_avg_vector) * np.linalg.norm(resume_avg_vector))

    # Set a threshold for similarity score to determine eligibility
    similarity_threshold = 0.8  # Adjust as needed

    # Assess eligibility based on cosine similarity
    if cosine_sim >= similarity_threshold:
        eligibility_status = "Eligible"
    else:
        eligibility_status = "Not Eligible"

    # Print cosine similarity and eligibility status
    print(f"Cosine Similarity: {cosine_sim}")
    print("Eligibility Status:", eligibility_status)
else:
    print("No word vectors found for job description or resume.")


Cosine Similarity: 0.9155762195587158
Eligibility Status: Eligible


In [ ]:
word_vectors['apple']

array([-0.5985   , -0.46321  ,  0.13001  , -0.019576 ,  0.4603   ,
       -0.3018   ,  0.8977   , -0.65634  ,  0.66858  , -0.49164  ,
        0.037557 , -0.050889 ,  0.6451   , -0.53882  , -0.3765   ,
       -0.04312  ,  0.51384  ,  0.17783  ,  0.28596  ,  0.92063  ,
       -0.49349  , -0.48583  ,  0.61321  ,  0.78211  ,  0.19254  ,
        0.91228  , -0.055596 , -0.12512  , -0.65688  ,  0.068557 ,
        0.55629  ,  1.611    , -0.0073642, -0.48879  ,  0.45493  ,
        0.96105  , -0.063369 ,  0.17432  ,  0.9814   , -1.3125   ,
       -0.15801  , -0.54301  , -0.13888  , -0.26146  , -0.3691   ,
        0.26844  , -0.24375  , -0.19484  ,  0.62583  , -0.7377   ,
        0.38351  , -0.75004  , -0.39053  ,  0.091498 , -0.36591  ,
       -1.4715   , -0.45228  ,  0.2256   ,  1.1412   , -0.38526  ,
       -0.06716  ,  0.57288  , -0.39191  ,  0.31302  , -0.29235  ,
       -0.96157  ,  0.15154  , -0.21659  ,  0.25103  ,  0.096967 ,
        0.2843   ,  1.4296   , -0.50565  , -0.51374  , -0.4721